// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { SkeletonConfigValue } from '../../slimevr-protocol/server/skeleton-config-value';


export class ChangeSkeletonConfigRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
__init(i:number, bb:flatbuffers.ByteBuffer):ChangeSkeletonConfigRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChangeSkeletonConfigRequest(bb:flatbuffers.ByteBuffer, obj?:ChangeSkeletonConfigRequest):ChangeSkeletonConfigRequest {
  return (obj || new ChangeSkeletonConfigRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChangeSkeletonConfigRequest(bb:flatbuffers.ByteBuffer, obj?:ChangeSkeletonConfigRequest):ChangeSkeletonConfigRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChangeSkeletonConfigRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():SkeletonConfigValue {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : SkeletonConfigValue.NONE;
}

value():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startChangeSkeletonConfigRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addId(builder:flatbuffers.Builder, id:SkeletonConfigValue) {
  builder.addFieldInt8(0, id, SkeletonConfigValue.NONE);
}

static addValue(builder:flatbuffers.Builder, value:number) {
  builder.addFieldFloat32(1, value, 0.0);
}

static endChangeSkeletonConfigRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChangeSkeletonConfigRequest(builder:flatbuffers.Builder, id:SkeletonConfigValue, value:number):flatbuffers.Offset {
  ChangeSkeletonConfigRequest.startChangeSkeletonConfigRequest(builder);
  ChangeSkeletonConfigRequest.addId(builder, id);
  ChangeSkeletonConfigRequest.addValue(builder, value);
  return ChangeSkeletonConfigRequest.endChangeSkeletonConfigRequest(builder);
}

unpack(): ChangeSkeletonConfigRequestT {
  return new ChangeSkeletonConfigRequestT(
    this.id(),
    this.value()
  );
}


unpackTo(_o: ChangeSkeletonConfigRequestT): void {
  _o.id = this.id();
  _o.value = this.value();
}
}

export class ChangeSkeletonConfigRequestT {
constructor(
  public id: SkeletonConfigValue = SkeletonConfigValue.NONE,
  public value: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ChangeSkeletonConfigRequest.createChangeSkeletonConfigRequest(builder,
    this.id,
    this.value
  );
}
}
